# Generated by Django 3.2.4 on 2021-07-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_callbackmodel_contactmodel_customerreviewmodel_slidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='superadmin.categorymodel'),
        ),
    ]
