# Generated by Django 3.2.4 on 2021-07-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20210708_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='image',
        ),
    ]
