# Generated by Django 3.2.4 on 2021-07-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_remove_contactmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerreviewmodel',
            name='image',
        ),
    ]
