# Generated by Django 3.2.4 on 2021-08-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_categoryimgmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryimgmodel',
            name='slug',
        ),
    ]
