# Generated by Django 3.2.4 on 2021-08-08 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_remove_categoryimgmodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/project/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectimg', to='superadmin.projectmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressImgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/progress/')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progressimg', to='superadmin.progressmodel')),
            ],
        ),
    ]
